name: Update Contribution Graph

on:
  schedule:
    - cron: '0 1 * * *'  # 每天凌晨1点运行
  workflow_dispatch:  # 允许手动触发
  push:
    branches: [ main ]  # 当main分支有推送时运行

jobs:
  update-contribution:
    runs-on: ubuntu-latest
    name: Update README with latest contribution graph

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests PyGithub
          
      - name: Update contribution graph
        run: |
          python .github/scripts/update_contribution.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Commit and push if changed
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add -A
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update contribution graph" && git push) 